### ISSUE TITLE
Conform to MVC design mattern

### ISSUE THREAD

**Issue by dramikei** [dramikei/kapde-wala-backend#2]
Currently the whole logic of this project resides in the index.js file. Try to split the code into the MVC design pattern.

Conforming to MVC shouldn't be hard, as the project itself isn't too complicated and consists only of a few GET and POST requests. Also since this is the API backend, there aren't any views so all one has to do in order to split the code into MVC is to create Model, Controller, Routes and probably Utils.

this is what I believe the project folder would look like after changing into MVC:

```
.
├── README.md
├── index.js
├── controllers
│   ├── user-controller.js
│   ├── login-controller.js
│   └── dhobi-controllers.js
├── models
│   ├── dhobi.js
│   ├── user.js
│   ├── order.js
│   └── login.js
├── nodemon.json
├── package-lock.json
├── package.json
└── routes
    ├── dhobi-routes.js
    └── user-routes.js

```

PS. The app is very simple and naive, (For example, "Login" just checks if the user details are available in the Login table, if it is then it returns a success else returns an error message)
There is no user authentication/authorization implemented, though you are free to implement it if you want.

Feel free to ask anything if you need any sort of help.

**Comment by asi309** [comment]
I can work on this issue. Please assign me

**Comment by dramikei** [comment]
Hey @asi309 ! feel free to work on the issue :)
